project_id = "plyzicpwvcqheubiidvn"

[functions.get-user-email]
verify_jwt = true

[functions.auth-with-rate-limit]
verify_jwt = false

[functions.consultar-cnpj]
verify_jwt = false

[functions.notify-ticket-created]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-service-orders-reminder]
verify_jwt = false

[functions.update-user]
verify_jwt = false